name: Python Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Install dependencies
        run: |
          uv sync

      - name: Lint with Ruff
        run: |
          uv run ruff check

      - name: Test with pytest
        run: |
          uv run pytest

      - name: Install CLI #this step is to verify if it can install
        run: |
          uv tool install . -e
      
      - name: Uninstall CLI #this step is to verify if it can uninstall
        run: |
          uv tool uninstall trsf
